# Generated by Django 4.2.5 on 2023-09-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
